# Advanced custom grouping configuration
# This file shows how to create more complex groupings for analysis

# Define custom groups that combine multiple run identifiers
[groups]
# Group all reward functions together
all_reward_functions = [
    "rf1",
    "rf4",
    "rf5",
    "rf6",
    "rf8",
    "rf9",
    "rf10",
    "rf11",
    "rf12",
    "rf13",
    "rf14",
]

# Compare early vs late reward functions
early_rf = ["rf1", "rf4", "rf5", "rf6"]
late_rf = ["rf10", "rf11", "rf12", "rf13", "rf14"]

# Best performing reward functions
best_performers = ["rf13", "rf14"]

# Baseline comparison
baseline_group = ["baseline"]

# Color overrides for specific groups (optional)
# These colors will override the default color palette
[group_colors]
all_reward_functions = "#2ca02c" # Green
early_rf = "#1f77b4"             # Blue  
late_rf = "#ff7f0e"              # Orange
best_performers = "#d62728"      # Red
baseline_group = "#9467bd"       # Purple
