# Color palette for graph lines
# Add more colors as needed
colors = [
    "#E69F00", # orange
    "#56B4E9", # sky blue
    "#009E73", # green
    "#F0E442", # yellow
    "#0072B2", # blue
    "#D55E00", # vermillion
    "#CC79A7", # pink
]
