# Graph styling settings

# Axis labels
x_axis_name = "Step"
y_axis_name = "Episodic Original Reward"

# Envelope (confidence band) opacity
envelope_opacity = 0.3

# Font settings
font_color = "#000000"
font_size = 12
font_weight = "normal"  # "normal", "bold", "light"

# Background and box colors
box_color = "#FFFFFF"

# Line settings
line_thickness = 2.0
line_width = 2.0

# Grid settings
grid_color = "#CCCCCC"
grid_thickness = 0.5